Repository hmcts/div-decree-nisi-frontend, pull requests merged in 2018-11, with the labels that each got.

#117 DIV-3496 Use static contact info
  steps/exit/Exit.html
  test/unit/steps/exit.test.js
Labels: ns:div-dn-pr-117

#121 Updated Jenkins pipeline config
  Jenkinsfile_CNP
Labels: ns:div-dn-pr-121

#129 Add some more tests for untested fields in mini-petition
  steps/mini-petition/MiniPetition.html
  test/unit/steps/miniPetition.test.js
Labels: ns:div-dn-pr-129

#130 Mini petition unit test update
  test/unit/steps/miniPetition.test.js
Labels: ns:div-dn-pr-130

#122 DIV-3499 Fixed feedback url
  app.js
  package.json
  test/w3cjs/index.js
  yarn.lock
Labels: ns:div-dn-pr-122

#132 Div 3040 no response page
  test/unit/steps/dnNoResponse.test.js
Labels: ns:div-dn-pr-132

#135 Code coverage failure
  steps/petition-progress-bar/PetitionProgressBar.step.js
Labels: ns:div-dn-pr-135

#118 Fix submit date issues
  helpers/caseOrchestrationHelper.js
  mocks/steps/modify-session/ModifySession.content.json
  mocks/steps/modify-session/ModifySession.step.js
  mocks/steps/modify-session/sections/petitioner.html
  package.json
  resources/sessionToCosMapping.json
  services/caseOrchestrationService.js
  steps/adultery-first-found-out/AdulteryFirstFoundOut.content.json
  steps/adultery-first-found-out/AdulteryFirstFoundOut.html
  steps/adultery-first-found-out/AdulteryFirstFoundOut.step.js
  steps/behaviour-continued-since-application/BehaviourContinuedSinceApplication.step.js
  steps/claim-costs/ClaimCosts.html
  steps/claim-costs/ClaimCosts.step.js
  steps/lived-apart-since-last-incident-date/LivedApartSinceLastIncidentDate.content.json
  test/e2e/journeys/sepereration2Years.test.js
  test/e2e/journeys/sepereration5Years.test.js
  test/unit/helpers/caseOrchestrationHelper.test.js
  test/unit/services/caseOrchestrationService.test.js
  test/unit/steps/adulteryFirstFoundOut.test.js
  test/unit/steps/claimCosts.test.js
  yarn.lock
Labels: ns:div-dn-pr-118

#128 Div 3463 e2
  helpers/caseOrchestrationHelper.js
  steps/adultery-first-found-out/AdulteryFirstFoundOut.step.js
  test/e2e/journeys/DivorceReasons/adultery.test.js
  test/e2e/journeys/DivorceReasons/desertion.test.js
  test/e2e/journeys/DivorceReasons/separation2Years.test.js
  test/e2e/journeys/DivorceReasons/separation5Years.test.js
  test/e2e/journeys/DivorceReasons/unreasonablebehaviour.test.js
  test/e2e/journeys/ccdStates/aosOverdue.js
  test/e2e/journeys/ccdStates/aosStarted.test.js
  test/e2e/journeys/ccdStates/awaitingLegalAdvisorReferal.test.js
  test/e2e/journeys/ccdStates/defendedDivorce.test.js
  test/e2e/journeys/ccdStates/dnAwaitingDeemedService.js
  test/e2e/journeys/ccdStates/dnAwaitingDefendedWithoutAnswer.js
  test/e2e/journeys/ccdStates/dnAwaitingDispensedWithService.js
  test/e2e/journeys/ccdStates/dnAwaitingUndefended.js
  test/e2e/journeys/ccdStates/submitted.test.js
Labels: ns:div-dn-pr-128

#140 added health check for cos
  middleware/healthcheck.js
Labels: ns:div-dn-pr-140

#143 fix petitioner progress bar tests
  package.json
  test/unit/steps/petitionerProgressBar.test.js
  yarn.lock
Labels: ns:div-dn-pr-143

#141 DIV-3491 - create functional integration case
  .gitignore
  Jenkinsfile_CNP
  README.md
  config/custom-environment-variables.yml
  config/default.yml
  infrastructure/main.tf
  infrastructure/variables.tf
  kubernetes/config.aat.yaml
  package.json
  services/idam.js
  steps/authenticated/Authenticated.step.js
  steps/entry/Entry.step.js
  steps/start/Start.step.js
  test/functional/codecept.conf.js
  test/functional/codecept.smoke.conf.js
  test/functional/helpers/JSWait.js
  test/functional/helpers/caseConfigHelper.js
  test/functional/helpers/caseHelper.js
  test/functional/helpers/idamConfigHelper.js
  test/functional/helpers/idamHelper.js
  test/functional/pages/checkYouAnswers.js
  test/functional/pages/claimCosts.js
  test/functional/pages/idam.step.js
  test/functional/pages/shareCourtDocuments.js
  test/functional/paths/intergration.js
  test/functional/paths/pages.js
  test/resources/basic-divorce-session.json
  test/unit/services/idam.test.js
  test/unit/steps/authenicated.test.js
  test/unit/steps/entry.test.js
  test/unit/steps/start.test.js
  yarn.lock
Labels: ns:div-dn-pr-141

#133 DIV-3505 Standard links shown under each page
  config/default.yml
  package.json
  steps/cookies-policy/CookiesPolicy.content.json
  steps/cookies-policy/CookiesPolicy.html
  steps/cookies-policy/CookiesPolicy.step.js
  steps/privacy-policy/PrivacyPolicy.content.json
  steps/privacy-policy/PrivacyPolicy.html
  steps/privacy-policy/PrivacyPolicy.step.js
  steps/terms-and-conditions/TermsAndConditions.content.json
  steps/terms-and-conditions/TermsAndConditions.html
  steps/terms-and-conditions/TermsAndConditions.step.js
  views/page.njk
  views/question.njk
  yarn.lock
Labels: ns:div-dn-pr-133

#152 Fix pre test step in pipeline
  Jenkinsfile_CNP
  test/e2e/journeys/DivorceReasons/adultery.test.js
  test/e2e/journeys/DivorceReasons/unreasonablebehaviour.test.js
Labels: ns:div-dn-pr-152

#153 Adding filter - otherwise href tags will not be converted
  steps/cookies-policy/CookiesPolicy.html
Labels: ns:div-dn-pr-153

#151 Updated cookie policy to make HTML and content cleaner
  steps/cookies-policy/CookiesPolicy.content.json
  steps/cookies-policy/CookiesPolicy.html
Labels: ns:div-dn-pr-151

#156 Fixed all high and critical security vulnerabilities
  package.json
  yarn.lock
Labels: ns:div-dn-pr-156

#136 Div 3533 review aos response dynamic content
  mocks/steps/modify-session/ModifySession.content.json
  mocks/steps/modify-session/ModifySession.step.js
  mocks/steps/modify-session/sections/caseState.html
  mocks/steps/modify-session/sections/respondent.html
  steps/petition-progress-bar/sections/defendedAwaitingAnswer/PetitionProgressBar.content.defendedAwaitingAnswer.json
  steps/petition-progress-bar/sections/defendedAwaitingAnswer/PetitionProgressBar.defendedAwaitingAnswer.template.html
  steps/review-aos-response/ReviewAosResponse.content.json
  steps/review-aos-response/ReviewAosResponse.html
  steps/review-aos-response/ReviewAosResponse.step.js
  steps/review-aos-response/templates/ReviewResponse.html
  steps/review-aos-response/templates/ViewResponse.html
  steps/review-aos-response/templates/costOrder.html
  steps/review-aos-response/templates/howRespondentProceed.html
  steps/review-aos-response/templates/jurisdiction.html
  test/e2e/journeys/ccdStates/AOSSubmittedAwaitingAnswer.js
  test/e2e/journeys/ccdStates/dnNoResponse.test.js
  test/unit/steps/reviewAosRespondent.test.js
  test/unit/steps/reviewAosResponse.test.js
Labels: ns:div-dn-pr-136

#155 Changes to statement of truth content
  steps/mini-petition/MiniPetition.content.json
  steps/mini-petition/MiniPetition.html
Labels: ns:div-dn-pr-155

#154 Changes to privacy policy
  steps/cookies-policy/CookiesPolicy.step.js
  steps/privacy-policy/PrivacyPolicy.content.json
  steps/privacy-policy/PrivacyPolicy.html
Labels: ns:div-dn-pr-154

#160 Testing on PR
  package.json
  yarn.lock
Labels: ns:div-dn-pr-160

#150 [PREVIEW] - remove start page and navigate directly to idam
  Jenkinsfile_CNP
  README.md
  infrastructure/output.tf
  package.json
  steps/start/Start.content.json
  steps/start/Start.html
  steps/start/Start.step.js
  test/functional/codecept.conf.js
  test/functional/codecept.smoke.conf.js
  test/functional/helpers/idamHelper.js
  test/functional/pages/cookie.step.js
  test/functional/pages/idam.step.js
  test/functional/pages/privacyPolicy.step.js
  test/functional/pages/start.step.js
  test/functional/pages/termsAndCondiction.step.js
  test/functional/paths/intergration.js
  test/functional/paths/pages.js
  test/functional/smoke/index.js
  test/unit/steps/start.test.js
  yarn.lock
Labels: ns:div-dn-pr-150

#144 Div 3549 cost diff amount option
  resources/sessionToCosMapping.json
  steps/claim-costs/ClaimCosts.content.json
  steps/claim-costs/ClaimCosts.html
  steps/claim-costs/ClaimCosts.step.js
  steps/mini-petition/MiniPetition.html
  test/e2e/journeys/DivorceReasons/adultery.test.js
  test/e2e/journeys/DivorceReasons/desertion.test.js
  test/e2e/journeys/DivorceReasons/separation2Years.test.js
  test/e2e/journeys/DivorceReasons/separation5Years.test.js
  test/e2e/journeys/DivorceReasons/unreasonablebehaviour.test.js
  test/e2e/journeys/ccdStates/aosOverdue.js
  test/e2e/journeys/ccdStates/dnAwaitingDeemedService.js
  test/e2e/journeys/ccdStates/dnAwaitingDefendedWithoutAnswer.js
  test/e2e/journeys/ccdStates/dnAwaitingDispensedWithService.js
  test/e2e/journeys/ccdStates/dnAwaitingUndefended.js
  test/functional/pages/claimCosts.js
  test/unit/steps/claimCosts.test.js
  yarn.lock
Labels: ns:div-dn-pr-144

#168 secure cookies
  app.js
  config/default.yml
Labels: ns:div-dn-pr-168

#167 DIV-3638 - point to hmcts/reform-pattern-library
  package.json
  yarn.lock
Labels: ns:div-dn-pr-167

#127 Redirect to d8
  config/custom-environment-variables.yml
  config/default.yml
  helpers/redirectToFrontendHelper.js
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/preview.tfvars
  infrastructure/variables.tf
  kubernetes/config.aat.yaml
  middleware/redirectToEntry.js
  mocks/services/case-orchestration/retrieve-aos-case/mock-case.json
  package.json
  services/caseOrchestrationService.js
  steps/authenticated/Authenticated.step.js
  steps/entry/Entry.step.js
  test/unit/helpers/redirectToFrontendHelper.test.js
  test/unit/middleware/redirectToEntry.test.js
  test/unit/services/caseOrchestrationService.test.js
  test/unit/steps/authenicated.test.js
  test/unit/steps/entry.test.js
  yarn.lock
Labels: ns:div-dn-pr-127

#175 Date formatted
  steps/exit/Exit.content.json
  steps/exit/Exit.html
  steps/mini-petition/MiniPetition.content.json
Labels: ns:div-dn-pr-175
