Repository hmcts/div-decree-nisi-frontend, pull requests merged in 2018-12, with the labels that each got.

#157 Family Man ref number shown
  config/default.yml
  infrastructure/main.tf
  kubernetes/config.aat.yaml
  mocks/services/case-orchestration/retrieve-case/GET.mock
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  services/caseOrchestrationService.js
  steps/authenticated/Authenticated.step.js
  steps/contact-divorce-team/ContactDivorceTeam.content.json
  steps/contact-divorce-team/ContactDivorceTeam.html
  steps/contact-divorce-team/ContactDivorceTeam.step.js
  steps/done/Done.html
  steps/done/Done.step.js
  steps/entry/Entry.step.js
  steps/petition-progress-bar/PetitionProgressBar.content.json
  steps/petition-progress-bar/PetitionProgressBar.html
  steps/petition-progress-bar/PetitionProgressBar.step.js
  steps/petition-progress-bar/petitionerStateTemplates.js
  steps/petition-progress-bar/sections/issued/PetitionProgressBar.content.issued.json
  steps/petition-progress-bar/sections/issued/PetitionProgressBar.issued.template.html
  steps/petition-progress-bar/sections/submitted/PetitionProgressBar.submitted.template.html
  test/e2e/journeys/DivorceReasons/adultery.test.js
  test/e2e/journeys/DivorceReasons/desertion.test.js
  test/e2e/journeys/DivorceReasons/separation2Years.test.js
  test/e2e/journeys/DivorceReasons/separation5Years.test.js
  test/e2e/journeys/DivorceReasons/unreasonablebehaviour.test.js
  test/e2e/journeys/ccdStates/AOSSubmittedAwaitingAnswer.js
  test/e2e/journeys/ccdStates/aosOverdue.js
  test/e2e/journeys/ccdStates/aosStarted.test.js
  test/e2e/journeys/ccdStates/awaitingLegalAdvisorReferal.test.js
  test/e2e/journeys/ccdStates/defendedDivorce.test.js
  test/e2e/journeys/ccdStates/dnAwaitingDeemedService.js
  test/e2e/journeys/ccdStates/dnAwaitingDefendedWithoutAnswer.js
  test/e2e/journeys/ccdStates/dnAwaitingDispensedWithService.js
  test/e2e/journeys/ccdStates/dnAwaitingUndefended.js
  test/e2e/journeys/ccdStates/dnNoResponse.test.js
  test/e2e/journeys/ccdStates/submitted.test.js
  test/functional/pages/contactDivorceTeam.js
  test/functional/paths/pages.js
  test/unit/services/caseOrchestrationService.test.js
  test/unit/services/googleAnalytics.test.js
  test/unit/steps/authenticated.test.js
  test/unit/steps/contactDivorceTeam.test.js
  test/unit/steps/done.test.js
  test/unit/steps/entry.test.js
  test/unit/steps/petitionerProgressBar.test.js
  test/w3cjs/index.js
  yarn.lock
Labels: ns:div-dn-pr-157

#171 Changed the way court information is displayed so that CTSC info is..
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  steps/dn-no-response/DnNoResponse.content.json
  steps/dn-no-response/DnNoResponse.html
  steps/done/Done.content.json
  steps/done/Done.html
  steps/petition-progress-bar/PetitionProgressBar.content.json
  steps/petition-progress-bar/PetitionProgressBar.html
  test/unit/helpers/courtInformation.js
  test/unit/resources/courtsList.json
  test/unit/steps/dnNoResponse.test.js
  test/unit/steps/done.test.js
  test/unit/steps/petitionerProgressBar.test.js
  views/includes/sideMenuCourtDetails.html
Labels: ns:div-dn-pr-171

#180 fix session editor
  mocks/steps/modify-session/ModifySession.step.js
  mocks/steps/modify-session/sections/rawSession.html
  test/unit/mock/steps/modifiySession.test.js
Labels: ns:div-dn-pr-180

#183 [PREVIEW] Fixed typo in yarn audit slack warning
  Jenkinsfile_CNP
Labels: ns:div-dn-pr-183

#182 DIV-3730 Added applyForDecreeNisi field on request
  resources/sessionToCosMapping.json
  test/e2e/journeys/DivorceReasons/adultery.test.js
  test/e2e/journeys/DivorceReasons/desertion.test.js
  test/e2e/journeys/DivorceReasons/separation2Years.test.js
  test/e2e/journeys/DivorceReasons/separation5Years.test.js
  test/e2e/journeys/DivorceReasons/unreasonablebehaviour.test.js
  test/e2e/journeys/ccdStates/aosOverdue.js
  test/e2e/journeys/ccdStates/dnAwaitingDeemedService.js
  test/e2e/journeys/ccdStates/dnAwaitingDefendedWithoutAnswer.js
  test/e2e/journeys/ccdStates/dnAwaitingDispensedWithService.js
  test/e2e/journeys/ccdStates/dnAwaitingUndefended.js
Labels: ns:div-dn-pr-182

#185 [PREVIEW] DIV-3620: Updated error pages to include standard links
  app.js
  package.json
  views/errors/error.html
  yarn.lock
Labels: ns:div-dn-pr-185

#177 [PREVIEW] - DN - Redirects to correct places based on specific criteria
  README.md
  app.js
  config/custom-environment-variables.yml
  config/default.yml
  helpers/caseOrchestrationHelper.js
  helpers/redirectToFrontendHelper.js
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/variables.tf
  kubernetes/config.aat.yaml
  middleware/redirectToEntry.js
  mocks/services/idam.js
  package.json
  services/caseOrchestrationService.js
  steps/authenticated/Authenticated.step.js
  steps/entry/Entry.step.js
  steps/exit/Exit.step.js
  test/e2e/journeys/DivorceReasons/adultery.test.js
  test/e2e/journeys/DivorceReasons/desertion.test.js
  test/e2e/journeys/DivorceReasons/separation2Years.test.js
  test/e2e/journeys/DivorceReasons/separation5Years.test.js
  test/e2e/journeys/DivorceReasons/unreasonablebehaviour.test.js
  test/e2e/journeys/ccdStates/AOSSubmittedAwaitingAnswer.js
  test/e2e/journeys/ccdStates/aosOverdue.js
  test/e2e/journeys/ccdStates/aosStarted.test.js
  test/e2e/journeys/ccdStates/awaitingLegalAdvisorReferal.test.js
  test/e2e/journeys/ccdStates/defendedDivorce.test.js
  test/e2e/journeys/ccdStates/dnAwaitingDeemedService.js
  test/e2e/journeys/ccdStates/dnAwaitingDefendedWithoutAnswer.js
  test/e2e/journeys/ccdStates/dnAwaitingDispensedWithService.js
  test/e2e/journeys/ccdStates/dnAwaitingUndefended.js
  test/e2e/journeys/ccdStates/dnNoResponse.test.js
  test/e2e/journeys/ccdStates/submitted.test.js
  test/functional/helpers/caseHelper.js
  test/unit/helpers/caseOrchestrationHelper.test.js
  test/unit/helpers/redirectToFrontendHelper.test.js
  test/unit/middleware/redirectToEntry.test.js
  test/unit/services/caseOrchestrationService.test.js
  test/unit/steps/authenticated.test.js
  test/unit/steps/entry.test.js
  yarn.lock
Labels: ns:div-dn-pr-177

#187 [PREVIEW] - Update health check for IDAM
  config/custom-environment-variables.yml
  config/default.yml
  infrastructure/main.tf
  kubernetes/config.aat.yaml
  middleware/healthcheck.js
  test/unit/middleware/healthcheck.test.js
Labels: ns:div-dn-pr-187

#188 Move idam auth to after assets
  app.js
Labels: ns:div-dn-pr-188

#181 Line break added for every line
  steps/mini-petition/MiniPetition.html
Labels: ns:div-dn-pr-181

#196 CYA confirmation content fix
  steps/check-your-answers/CheckYourAnswers.html
  steps/check-your-answers/CheckYourAnswers.step.js
  test/unit/steps/checkYouAnswers.test.js
Labels: ns:div-dn-pr-196

#191 DIV-3812 Revert idam health-check to not need the proxy
  middleware/healthcheck.js
  test/unit/middleware/healthcheck.test.js
Labels: ns:div-dn-pr-191

#198 Other proceedings content added
  steps/review-aos-response/ReviewAosResponse.content.json
  steps/review-aos-response/templates/jurisdiction.html
  test/unit/steps/reviewAosResponse.test.js
Labels: ns:div-dn-pr-198

#193 DN-Only selected answers to be sent to ccd
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  resources/sessionToCosMapping.json
  steps/claim-costs/ClaimCosts.content.json
  steps/claim-costs/ClaimCosts.html
  steps/claim-costs/ClaimCosts.step.js
  steps/lived-apart-since-adultery/LivedApartSinceAdultery.step.js
  steps/lived-apart-since-desertion/LivedApartSinceDesertion.step.js
  steps/lived-apart-since-last-incident-date/LivedApartSinceLastIncidentDate.step.js
  steps/lived-apart-since-separation/LivedApartSinceSeparation.step.js
  steps/mini-petition/MiniPetition.step.js
  test/e2e/journeys/DivorceReasons/adultery.test.js
  test/unit/steps/claimCosts.test.js
  test/unit/steps/livedApartSinceAdultery.test.js
  test/unit/steps/livedApartSinceDesertion.test.js
  test/unit/steps/livedApartSinceLastIncidentDate.test.js
  test/unit/steps/livedApartSinceSeparation.test.js
  test/unit/steps/miniPetition.test.js
Labels: ns:div-dn-pr-193
