Repository hmcts/div-decree-nisi-frontend, pull requests merged in 2019-03, with the labels that each got.

#278 DIV-4362: Force updated Braces to remove 88 vulns & fix broken build
  Dockerfile
  package.json
  yarn.lock
Labels: ns:div-dn-pr-278

#277 Desertion agreement details added to mini petition
  steps/mini-petition/MiniPetition.content.json
  steps/mini-petition/MiniPetition.html
  test/unit/steps/miniPetition.test.js
Labels: ns:div-dn-pr-277

#283 DN- Adding adultery second hand info in mini petiiton
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  steps/mini-petition/MiniPetition.content.json
  steps/mini-petition/MiniPetition.html
  test/unit/steps/miniPetition.test.js
Labels: ns:div-dn-pr-283

#274 Adultery corespondent response step
  config/default.yml
  steps/resp-not-admit-adultery/RespNotAdmitAdultery.step.js
  steps/review-aos-response-from-co-respondent/ReviewAosResponseFromCoRespondent.content.json
  steps/review-aos-response-from-co-respondent/ReviewAosResponseFromCoRespondent.html
  steps/review-aos-response-from-co-respondent/ReviewAosResponseFromCoRespondent.step.js
  steps/review-aos-response/ReviewAosResponse.step.js
  test/e2e/journeys/DivorceReasons/adultery.test.js
  test/functional/pages/reviewAosResponseFromCoRespondent.js
  test/functional/paths/pages.js
  test/unit/steps/respNotAdmitAdultery.test.js
  test/unit/steps/reviewAosResponse.test.js
  test/unit/steps/reviewAosResponseFromCoRespondent.test.js
  yarn.lock
Labels: ns:div-dn-pr-274

#289 Added release520 flag check on adulterysecondhandinfo
  steps/mini-petition/MiniPetition.html
  steps/mini-petition/MiniPetition.step.js
  test/unit/steps/miniPetition.test.js
Labels: ns:div-dn-pr-289

#285 CoRespondent answers should be updated in DN CYA page
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  steps/review-aos-response-from-co-respondent/ReviewAosResponseFromCoRespondent.content.json
  steps/review-aos-response-from-co-respondent/ReviewAosResponseFromCoRespondent.html
  steps/review-aos-response-from-co-respondent/ReviewAosResponseFromCoRespondent.step.js
  test/e2e/journeys/DivorceReasons/adultery.test.js
  test/unit/steps/respNotAdmitAdultery.test.js
  test/unit/steps/reviewAosResponseFromCoRespondent.test.js
Labels: ns:div-dn-pr-285

#291 Ga settings update 4363
  infrastructure/prod.tfvars
  middleware/helmet.js
  test/unit/middleware/helmet.test.js
  test/unit/services/googleAnalytics.test.js
  views/includes/head.html
Labels: ns:div-dn-pr-291

#284 DIV-4416 Use a re-direct if case is in AmendPetition state
  config/default.yml
  test/unit/helpers/caseOrchestrationHelper.test.js
Labels: ns:div-dn-pr-284

#295 Content update adultery amend petition
  steps/petition-progress-bar/sections/aosCompleted/PetitionProgressBar.aosCompleted.template.html
  steps/petition-progress-bar/sections/aosCompleted/PetitionProgressBar.content.aosCompleted.json
  steps/resp-not-admit-adultery/RespNotAdmitAdultery.content.json
  steps/resp-not-admit-adultery/RespNotAdmitAdultery.html
Labels: ns:div-dn-pr-295

#281 update content for mini petition help section
  steps/mini-petition/MiniPetition.content.json
  steps/mini-petition/MiniPetition.html
Labels: ns:div-dn-pr-281

#288 Setup SAAT and SIDAM
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  config/custom-environment-variables.yml
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/preview.tfvars
  infrastructure/saat.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
  infrastructure/state.tf
  kubernetes/config.aat.yaml
  middleware/healthcheck.js
  package.json
  test/functional/helpers/caseHelper.js
  test/functional/helpers/idamHelper.js
  yarn.lock
Labels: ns:div-dn-pr-288

#296 DN-Co-respondent - spelling issue
  steps/adultery-first-found-out/AdulteryFirstFoundOut.step.js
  steps/behaviour-continued-since-application/BehaviourContinuedSinceApplication.step.js
  steps/review-aos-response-from-co-respondent/ReviewAosResponseFromCoRespondent.content.json
  test/unit/steps/adulteryFirstFoundOut.test.js
  test/unit/steps/behaviourContinuedSinceApplication.test.js
Labels: ns:div-dn-pr-296

#280 fix stale data on lived apart since adultery
  package.json
  steps/lived-apart-since-adultery/LivedApartSinceAdultery.step.js
  test/unit/steps/livedApartSinceAdultery.test.js
  yarn.lock
Labels: ns:div-dn-pr-280

#290 Div 4450 Change DN workflow to display Resp/CoResp responses before showing amend petition
  steps/resp-not-admit-adultery/RespNotAdmitAdultery.step.js
  steps/review-aos-response-from-co-respondent/ReviewAosResponseFromCoRespondent.step.js
  steps/review-aos-response/ReviewAosResponse.step.js
  test/e2e/journeys/DivorceReasons/adultery.test.js
  test/unit/steps/respNotAdmitAdultery.test.js
  test/unit/steps/reviewAosResponse.test.js
  test/unit/steps/reviewAosResponseFromCoRespondent.test.js
Labels: ns:div-dn-pr-290
