Repository hmcts/div-decree-nisi-frontend, pull requests merged in 2019-04, with the labels that each got.

#305 If respondentAnswer is not available the CYA page should not be blocked
  steps/review-aos-response/ReviewAosResponse.step.js
Labels: ns:div-dn-pr-305

#282 DIV-4386: Added phrase to privacy policy page
  steps/privacy-policy/PrivacyPolicy.content.json
  steps/privacy-policy/PrivacyPolicy.html
  test/unit/steps/privacyPolicy.test.js
Labels: ns:div-dn-pr-282

#312 Disable prod deployments
  Jenkinsfile_CNP
Labels: ns:div-dn-pr-312

#303 Line break filter added
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  steps/mini-petition/MiniPetition.html
  steps/review-aos-response-from-co-respondent/ReviewAosResponseFromCoRespondent.html
  steps/review-aos-response/templates/howRespondentProceed.html
  steps/review-aos-response/templates/jurisdiction.html
Labels: ns:div-dn-pr-303

#314 Regenerate the Yarn Lock file
  yarn.lock
Labels: ns:div-dn-pr-314

#299 Changes to mini petiiton - show amend case & reissue date
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  steps/mini-petition/MiniPetition.content.json
  steps/mini-petition/MiniPetition.html
  test/unit/steps/miniPetition.test.js
Labels: ns:div-dn-pr-299

#292 Mini petition jurisdiction should match with ccd data
  steps/mini-petition/MiniPetition.html
  test/unit/steps/miniPetition.test.js
Labels: ns:div-dn-pr-292

#320 DIV-4691 - Moved setting of CI env variable in Jenkinsfile
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  config/ci.yml
Labels: ns:div-dn-pr-320

#319 DIV-4669 Enable release520
  config/default.yml
  infrastructure/preview.tfvars
  infrastructure/variables.tf
  kubernetes/config.aat.yaml
Labels: ns:div-dn-pr-319

#309 DIV-3773 Added helm chart config
  Jenkinsfile_CNP
  charts/div-dn/Chart.yaml
  charts/div-dn/requirements.yaml
  charts/div-dn/values.aat.template.yaml
  charts/div-dn/values.preview.template.yaml
  charts/div-dn/values.yaml
  helpers/setupSecretsHelper.js
  kubernetes/config.aat.yaml
  kubernetes/deployment.template.yaml
  middleware/healthcheck.js
  package.json
  server.js
  test/functional/helpers/idamHelper.js
  test/unit/helpers/setupSecretsHelper.test.js
  test/unit/middleware/healthcheck.test.js
  yarn.lock
Labels: ns:div-dn-pr-309

#328 Moved tags to a more appropiate position
  charts/div-dn/values.preview.template.yaml
Labels: ns:div-dn-pr-328

#321 Behaviour case - respAdmitOrConsentToFact field not available show correct content
  steps/petition-progress-bar/PetitionProgressBar.step.js
  steps/petition-progress-bar/sections/aosCompleted/PetitionProgressBar.aosCompleted.template.html
  steps/petition-progress-bar/sections/undefended/PetitionProgressBar.undefended.template.html
  test/unit/steps/petitionerProgressBar.test.js
Labels: ns:div-dn-pr-321

#330 Div 4504 petitioner download docs
  app.js
  assets/scss/main.scss
  charts/div-dn/values.aat.template.yaml
  charts/div-dn/values.preview.template.yaml
  config/custom-environment-variables.yml
  config/default.yml
  infrastructure/main.tf
  infrastructure/variables.tf
  middleware/healthcheck.js
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  mocks/services/documents/401ab79e-34cb-4570-9f2f-4cf9357m4st3r/GET.mock
  package.json
  services/documentHandler.js
  services/evidenceManagmentService.js
  steps/petition-progress-bar/PetitionProgressBar.content.json
  steps/petition-progress-bar/PetitionProgressBar.html
  steps/petition-progress-bar/PetitionProgressBar.step.js
  test/unit/services/documentHandler.test.js
  test/unit/steps/petitionerProgressBar.test.js
  test/unit/views/filters/upper.test.js
  views/filters/upper.js
  views/includes/guidanceOnGovUK.html
  yarn.lock
Labels: ns:div-dn-pr-330

#331 Date validation changes
  package.json
  steps/adultery-first-found-out/AdulteryFirstFoundOut.content.json
  steps/adultery-first-found-out/AdulteryFirstFoundOut.step.js
  steps/behaviour-continued-since-application/BehaviourContinuedSinceApplication.step.js
  test/unit/steps/behaviourContinuedSinceApplication.test.js
  yarn.lock
Labels: ns:div-dn-pr-331
