Repository hmcts/div-decree-nisi-frontend, pull requests merged in 2019-07, with the labels that each got.

#364 DIV-5103 - Update email address for divorce cases
  common/content.json
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  steps/contact-divorce-team-error/ContactDivorceTeamError.content.json
  steps/contact-divorce-team/ContactDivorceTeam.content.json
  steps/dn-no-response/DnNoResponse.content.json
  steps/done/Done.content.json
  steps/petition-progress-bar/PetitionProgressBar.content.json
  test/unit/resources/courtsList.json
Labels: ns:div-dn-pr-364

#368 DIV-5167 - Add state "DNPronounced"
  middleware/checkCaseState.js
  mocks/steps/modify-session/sections/caseState.html
  steps/petition-progress-bar/petitionerStateTemplates.js
  test/e2e/journeys/ccdStates/dnPronounced.test.js
  test/unit/middleware/checkCheckState.test.js
  test/unit/steps/petitionerProgressBar.test.js
Labels: ns:div-dn-pr-368

#369 DIV-5168: Updated routing logic to include DA
  charts/div-dn/values.aat.template.yaml
  charts/div-dn/values.preview.template.yaml
  config/custom-environment-variables.yml
  config/default.yml
  helpers/caseOrchestrationHelper.js
  helpers/redirectToFrontendHelper.js
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/saat.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
  infrastructure/variables.tf
  test/e2e/journeys/ccdStates/awaitingDecreeAbsolute.test.js
  test/unit/helpers/caseOrchestrationHelper.test.js
  test/unit/helpers/redirectToFrontendHelper.test.js
Labels: ns:div-dn-pr-369

#372 Added missing DA frontend URL in main.tf
  infrastructure/main.tf
Labels: ns:div-dn-pr-372

#371 Added new DA eligible case state
  config/default.yml
Labels: ns:div-dn-pr-371

#374 Update npm dependencies
  package.json
  yarn.lock
Labels: ns:div-dn-pr-374

#361 Div 5021 desertion ques added
  config/default.yml
  resources/sessionToCosMapping.json
  steps/desertion-asked-to-resume-dn/DesertionAskedToResumeDN.content.json
  steps/desertion-asked-to-resume-dn/DesertionAskedToResumeDN.html
  steps/desertion-asked-to-resume-dn/DesertionAskedToResumeDN.step.js
  steps/mini-petition/MiniPetition.step.js
  test/e2e/journeys/DivorceReasons/desertion.test.js
  test/functional/pages/desertionAskedToResumeDN.js
  test/functional/paths/pages.js
  test/unit/steps/desertionAskedToResumeDN.test.js
  test/unit/steps/miniPetition.test.js
Labels: ns:div-dn-pr-361

#376 Update to use the public HMCTS docker registry
  Dockerfile
  acb.tpl.yaml
Labels: ns:div-dn-pr-376

#377 check-your-answers page <dl> layout changed to <table> layout
  steps/check-your-answers/CheckYourAnswers.content.json
  steps/check-your-answers/CheckYourAnswers.html
  views/check-your-answers.njk
Labels: ns:div-dn-pr-377

#379 Revert "check-your-answers page <dl> layout changed to <table> layout"
  steps/check-your-answers/CheckYourAnswers.content.json
  steps/check-your-answers/CheckYourAnswers.html
  views/check-your-answers.njk
Labels: ns:div-dn-pr-379

#375 DIV-4858 - Front-end changes to show the documents
  config/default.yml
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  steps/petition-progress-bar/PetitionProgressBar.content.json
  test/unit/steps/petitionerProgressBar.test.js
Labels: ns:div-dn-pr-375

#381 DIV-5497: Temporary solution to prevent old paper based cases redirecting to DA
  helpers/caseOrchestrationHelper.js
  test/unit/helpers/caseOrchestrationHelper.test.js
Labels: ns:div-dn-pr-381

#383 Update yarn lock to try to fix pipeline node_module issues
  yarn.lock
Labels: ns:div-dn-pr-383

#384 change domain
  test/functional/helpers/idamHelper.js
Labels: ns:div-dn-pr-384
