Repository hmcts/div-decree-nisi-frontend, pull requests merged in 2019-05, with the labels that each got.

#337 configure nightly pipeline
  Jenkinsfile_nightly
  bin/run-crossbrowser-tests.sh
  config/custom-environment-variables.yml
  config/default.yml
  package.json
  test/crossbrowser/supportedBrowsers.js
  test/functional/helpers/SauceLabsReportingHelper.js
  test/functional/helpers/urlHelper.js
  test/functional/pages/idam.step.js
  test/functional/paths/intergration.js
  test/functional/saucelabs.conf.js
  yarn.lock
Labels: ns:div-dn-pr-337

#339 fixtypo
  test/functional/saucelabs.conf.js
Labels: ns:div-dn-pr-339

#340 add security scan to nightly pipeline
  security.sh
Labels: ns:div-dn-pr-340

#335 PermittedDNReason4 is added
  steps/petition-progress-bar/petitionerStateTemplates.js
  steps/review-aos-response/ReviewAosResponse.step.js
  test/unit/steps/petitionerProgressBar.test.js
  test/unit/steps/reviewAosResponse.test.js
Labels: ns:div-dn-pr-335

#294 Fix stale data on CCD when submitting DN to CCD
  helpers/caseOrchestrationHelper.js
  test/e2e/journeys/DivorceReasons/adultery.test.js
  test/e2e/journeys/DivorceReasons/desertion.test.js
  test/e2e/journeys/DivorceReasons/separation2Years.test.js
  test/e2e/journeys/DivorceReasons/separation5Years.test.js
  test/e2e/journeys/DivorceReasons/unreasonablebehaviour.test.js
  test/e2e/journeys/ccdStates/aosOverdue.js
  test/e2e/journeys/ccdStates/dnAwaitingDeemedService.js
  test/e2e/journeys/ccdStates/dnAwaitingDefendedWithoutAnswer.js
  test/e2e/journeys/ccdStates/dnAwaitingDispensedWithService.js
  test/e2e/journeys/ccdStates/dnAwaitingUndefended.js
  test/unit/helpers/caseOrchestrationHelper.test.js
Labels: ns:div-dn-pr-294

#342 suppress false positives
  security.sh
  zapKnownIssues.xml
Labels: ns:div-dn-pr-342

#344 Fix download end-point config
  infrastructure/variables.tf
Labels: ns:div-dn-pr-344

#327 Point to SIDAM
  Jenkinsfile_CNP
  infrastructure/demo.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
Labels: ns:div-dn-pr-327

#333 DIV-4396 Add respondent answers to downloadable docs
  config/default.yml
  mocks/index.js
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  mocks/services/documents/401ab79e-34cb-4570-9f2f-4cf9357m4st3r/GET.mock
  mocks/services/emclientapi/version/1/download/__/GET.mock
  steps/petition-progress-bar/PetitionProgressBar.content.json
Labels: ns:div-dn-pr-333

#334 DIV-4492: Added warning to inform users to download docs before amending
  README.md
  config/local.yml
  server.js
  steps/petition-progress-bar/PetitionProgressBar.content.json
  steps/petition-progress-bar/sections/aosCompleted/PetitionProgressBar.aosCompleted.template.html
Labels: ns:div-dn-pr-334

#347 DIV-4852 Add jquery hook for on click submit button to disable it
  assets/js/main.js
Labels: ns:div-dn-pr-347

#346 DIV-4860 - update the divorce contact email to contactdivorce@...
  common/content.json
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  steps/contact-divorce-team-error/ContactDivorceTeamError.content.json
  steps/contact-divorce-team/ContactDivorceTeam.content.json
  steps/dn-no-response/DnNoResponse.content.json
  steps/done/Done.content.json
  steps/petition-progress-bar/PetitionProgressBar.content.json
  test/unit/resources/courtsList.json
Labels: ns:div-dn-pr-346

#341 Div 4797 add co-resp answers doc to DN app
  config/default.yml
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  steps/petition-progress-bar/PetitionProgressBar.content.json
Labels: ns:div-dn-pr-341
