Repository hmcts/div-decree-nisi-frontend, pull requests merged in 2019-01, with the labels that each got.

#206 Enable CSRF functionality
  app.js
  assets/js/documentUpload.js
  steps/petition-progress-bar/sections/undefended/PetitionProgressBar.undefended.template.html
  steps/upload/Upload.html
  views/check-your-answers.njk
Labels: ns:div-dn-pr-206

#208 Sanitise request body on question step
  package.json
  yarn.lock
Labels: ns:div-dn-pr-208

#210 DIV-3830: Change to use gmail email address for int tests
  test/functional/helpers/idamHelper.js
Labels: ns:div-dn-pr-210

#202 Review aos response changes
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  mocks/steps/modify-session/ModifySession.step.js
  mocks/steps/modify-session/sections/respondent.html
  steps/petition-progress-bar/PetitionProgressBar.step.js
  steps/review-aos-response/ReviewAosResponse.content.json
  steps/review-aos-response/ReviewAosResponse.step.js
  steps/review-aos-response/templates/costOrder.html
  steps/review-aos-response/templates/howRespondentProceed.html
  steps/review-aos-response/templates/jurisdiction.html
  test/e2e/journeys/DivorceReasons/adultery.test.js
  test/e2e/journeys/DivorceReasons/desertion.test.js
  test/e2e/journeys/DivorceReasons/separation2Years.test.js
  test/e2e/journeys/DivorceReasons/separation5Years.test.js
  test/e2e/journeys/DivorceReasons/unreasonablebehaviour.test.js
  test/e2e/journeys/ccdStates/AOSSubmittedAwaitingAnswer.js
  test/e2e/journeys/ccdStates/aosOverdue.js
  test/e2e/journeys/ccdStates/aosStarted.test.js
  test/e2e/journeys/ccdStates/awaitingLegalAdvisorReferal.test.js
  test/e2e/journeys/ccdStates/defendedDivorce.test.js
  test/e2e/journeys/ccdStates/dnAwaitingDeemedService.js
  test/e2e/journeys/ccdStates/dnAwaitingDefendedWithoutAnswer.js
  test/e2e/journeys/ccdStates/dnAwaitingDispensedWithService.js
  test/e2e/journeys/ccdStates/dnAwaitingUndefended.js
  test/e2e/journeys/ccdStates/submitted.test.js
  test/unit/steps/petitionerProgressBar.test.js
  test/unit/steps/reviewAosResponse.test.js
Labels: ns:div-dn-pr-202

#207 Added has changes field on DN
  resources/sessionToCosMapping.json
  steps/mini-petition/MiniPetition.step.js
  test/e2e/journeys/DivorceReasons/adultery.test.js
  test/e2e/journeys/DivorceReasons/desertion.test.js
  test/e2e/journeys/DivorceReasons/separation2Years.test.js
  test/e2e/journeys/DivorceReasons/separation5Years.test.js
  test/e2e/journeys/DivorceReasons/unreasonablebehaviour.test.js
  test/e2e/journeys/ccdStates/aosOverdue.js
  test/e2e/journeys/ccdStates/dnAwaitingDeemedService.js
  test/e2e/journeys/ccdStates/dnAwaitingDefendedWithoutAnswer.js
  test/e2e/journeys/ccdStates/dnAwaitingDispensedWithService.js
  test/e2e/journeys/ccdStates/dnAwaitingUndefended.js
Labels: ns:div-dn-pr-207

#218 DIV-3915: Text change in claim costs in DN Journey
  helpers/caseOrchestrationHelper.js
  steps/claim-costs/ClaimCosts.content.json
  test/unit/steps/checkYouAnswers.test.js
Labels: ns:div-dn-pr-218

#220 Updating text according to Neil
  steps/claim-costs/ClaimCosts.content.json
Labels: ns:div-dn-pr-220

#224 DIV-3930 set prod urls
  .dockerignore
  infrastructure/prod.tfvars
Labels: ns:div-dn-pr-224

#229 Move to shared ASP 1
  infrastructure/main.tf
Labels: ns:div-dn-pr-229

#230 Add GA Tracking ID to Prod
  infrastructure/prod.tfvars
Labels: ns:div-dn-pr-230

#234 Fix healthcheck test
  middleware/healthcheck.js
  test/unit/middleware/healthcheck.test.js
Labels: ns:div-dn-pr-234

#226 [PREVIEW] DIV-3853 Apply infra for app insights config
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:div-dn-pr-226

#215 Revert dot to hyphen references in OPP
  package.json
  test/e2e/journeys/DivorceReasons/adultery.test.js
  test/e2e/journeys/DivorceReasons/desertion.test.js
  test/e2e/journeys/DivorceReasons/separation2Years.test.js
  test/e2e/journeys/DivorceReasons/separation5Years.test.js
  test/e2e/journeys/DivorceReasons/unreasonablebehaviour.test.js
  test/e2e/journeys/ccdStates/aosOverdue.js
  test/e2e/journeys/ccdStates/dnAwaitingDeemedService.js
  test/e2e/journeys/ccdStates/dnAwaitingDefendedWithoutAnswer.js
  test/e2e/journeys/ccdStates/dnAwaitingDispensedWithService.js
  test/e2e/journeys/ccdStates/dnAwaitingUndefended.js
  test/functional/pages/livedApartSinceAdultery.js
  test/unit/steps/adulteryFirstFoundOut.test.js
  test/unit/steps/behaviourContinuedSinceApplication.test.js
  test/unit/steps/claimCosts.test.js
  test/unit/steps/livedApartSinceAdultery.test.js
  test/unit/steps/livedApartSinceDesertion.test.js
  test/unit/steps/livedApartSinceLastIncidentDate.test.js
  test/unit/steps/livedApartSinceSeparation.test.js
  test/unit/steps/miniPetition.test.js
  test/w3cjs/index.js
  yarn.lock
Labels: ns:div-dn-pr-215

#237 Revert hyphen to dot
  package.json
  test/e2e/journeys/DivorceReasons/adultery.test.js
  test/e2e/journeys/DivorceReasons/desertion.test.js
  test/e2e/journeys/DivorceReasons/separation2Years.test.js
  test/e2e/journeys/DivorceReasons/separation5Years.test.js
  test/e2e/journeys/DivorceReasons/unreasonablebehaviour.test.js
  test/e2e/journeys/ccdStates/aosOverdue.js
  test/e2e/journeys/ccdStates/dnAwaitingDeemedService.js
  test/e2e/journeys/ccdStates/dnAwaitingDefendedWithoutAnswer.js
  test/e2e/journeys/ccdStates/dnAwaitingDispensedWithService.js
  test/e2e/journeys/ccdStates/dnAwaitingUndefended.js
  test/functional/pages/livedApartSinceAdultery.js
  test/unit/steps/adulteryFirstFoundOut.test.js
  test/unit/steps/behaviourContinuedSinceApplication.test.js
  test/unit/steps/claimCosts.test.js
  test/unit/steps/livedApartSinceAdultery.test.js
  test/unit/steps/livedApartSinceDesertion.test.js
  test/unit/steps/livedApartSinceLastIncidentDate.test.js
  test/unit/steps/livedApartSinceSeparation.test.js
  test/unit/steps/miniPetition.test.js
  test/w3cjs/index.js
  yarn.lock
Labels: ns:div-dn-pr-237

#241 add idam id and ccd id to logs
  app.js
  helpers/redirectToFrontendHelper.js
  middleware/evidenceManagmentMiddleware.js
  middleware/healthcheck.js
  server.js
  services/caseOrchestrationService.js
  services/evidenceManagmentService.js
  services/fileManagement.js
  services/logger.js
  services/redis.js
  test/unit/services/logger.test.js
Labels: ns:div-dn-pr-241

#228 Optimise docker image build layers
  .dockerignore
  Dockerfile
Labels: ns:div-dn-pr-228

#184 Update review petition page with 5 year separation dates
  steps/mini-petition/MiniPetition.content.json
  steps/mini-petition/MiniPetition.html
  test/unit/steps/miniPetition.test.js
Labels: ns:div-dn-pr-184

#222 Respondent user check condition modified
  helpers/caseOrchestrationHelper.js
  test/unit/helpers/caseOrchestrationHelper.test.js
Labels: ns:div-dn-pr-222

#249 Revert: Optimise docker image build layers (#228)
  .dockerignore
  Dockerfile
Labels: ns:div-dn-pr-249

#247 DIV-4122: Update e2e test for behaviour case
  README.md
  test/functional/helpers/caseHelper.js
  test/functional/pages/miniPetition.js
  test/functional/paths/intergration.js
  test/resources/basic-divorce-session.json
Labels: ns:div-dn-pr-247

#246 DIV-4038 improve logging
  helpers/redirectToFrontendHelper.js
  middleware/evidenceManagmentMiddleware.js
  middleware/healthcheck.js
  server.js
  services/app-insights.js
  services/caseOrchestrationService.js
  services/evidenceManagmentService.js
  services/fileManagement.js
  services/logger.js
  services/redis.js
  test/functional/helpers/caseHelper.js
  test/functional/helpers/idamHelper.js
  test/unit/middleware/healthcheck.test.js
  test/unit/services/app-insights.test.js
  test/unit/services/logger.test.js
Labels: ns:div-dn-pr-246
