Repository hmcts/div-decree-nisi-frontend, pull requests merged in 2019-10, with the labels that each got.

#397 DIV-4587 - Accessibility [AA]: Ambiguous links
  assets/js/documentUpload.js
  package.json
  steps/contact-divorce-team-error/ContactDivorceTeamError.html
  steps/contact-divorce-team/ContactDivorceTeam.html
  steps/cookies-policy/CookiesPolicy.content.json
  steps/dn-no-response/DnNoResponse.content.json
  steps/done/Done.content.json
  steps/mini-petition/MiniPetition.html
  steps/petition-progress-bar/PetitionProgressBar.content.json
  steps/privacy-policy/PrivacyPolicy.content.json
  steps/review-aos-response-from-co-respondent/ReviewAosResponseFromCoRespondent.html
  steps/review-aos-response/templates/costOrder.html
  steps/review-aos-response/templates/howRespondentProceed.html
  steps/review-aos-response/templates/jurisdiction.html
  steps/terms-and-conditions/TermsAndConditions.content.json
  steps/upload/Upload.html
  views/check-your-answers.njk
  views/includes/sideMenu.html
  yarn.lock
Labels: ns:div-dn-pr-397

#419 Webchats - add live environment variables
  infrastructure/prod.tfvars
Labels: ns:div-dn-pr-419

#420 DIV-5914 - Use the correct opening hours for the website messages
  common/content.json
Labels: ns:div-dn-pr-420

#425 AKS migration preparation
  .editorconfig
  charts/div-dn/Chart.yaml
  charts/div-dn/requirements.yaml
  charts/div-dn/values.aat.template.yaml
  charts/div-dn/values.preview.template.yaml
  charts/div-dn/values.yaml
  config/custom-environment-variables.yml
  config/default.yml
  config/production.yml
  helpers/setupSecretsHelper.js
  infrastructure/.gitignore
  infrastructure/main.tf
  infrastructure/variables.tf
  middleware/healthcheck.js
  package.json
  services/app-insights.js
  services/rateLimiter.js
  test/unit/services/app-insights.test.js
  yarn.lock
Labels: ns:div-dn-pr-425

#421 DIV-5756 - Enable webchat on live environment
  charts/div-dn/values.preview.template.yaml
  config/default.yml
  infrastructure/variables.tf
Labels: ns:div-dn-pr-421

#427 Update error show condition for production env as well
  views/errors/error.html
Labels: ns:div-dn-pr-427

#430 Enable chart publishing and fix typo
  Jenkinsfile_CNP
  helpers/setupSecretsHelper.js
Labels: ns:div-dn-pr-430

#428 Update of copy on Response Submitted (after clarification) done page
  steps/done/Done.content.json
  steps/done/Done.html
  steps/done/Done.step.js
  test/unit/steps/done.test.js
Labels: ns:div-dn-pr-428

#431 Change base image to alpine
  Dockerfile
  acb.tpl.yaml
  docker-compose.yaml
  package.json
  test/functional/codecept.conf.js
  test/functional/codecept.smoke.conf.js
  test/functional/saucelabs.conf.js
  yarn.lock
Labels: ns:div-dn-pr-431

#433 Removed unnecessary dependency and added resolution
  package.json
  yarn.lock
Labels: ns:div-dn-pr-433

#423 DIV-4725 - Petitioner Landing Page: DN Refusal (rejected)
  charts/div-dn/values.preview.template.yaml
  charts/div-dn/values.yaml
  common/constants.js
  config/custom-environment-variables.yml
  config/default.yml
  infrastructure/main.tf
  infrastructure/variables.tf
  middleware/checkCaseState.js
  mocks/services/case-orchestration/amend-petition-dn-rejection/__/PUT.mock
  mocks/steps/modify-session/ModifySession.step.js
  mocks/steps/modify-session/sections/caseState.html
  package.json
  services/caseOrchestrationService.js
  steps/petition-progress-bar/PetitionProgressBar.step.js
  steps/petition-progress-bar/petitionerStateTemplates.js
  steps/petition-progress-bar/sections/dnIsRefused/PetitionProgressBar.content.dnIsRefused.json
  steps/petition-progress-bar/sections/dnIsRefused/PetitionProgressBar.dnIsRefused.template.html
  test/e2e/journeys/ccdStates/diIsRefused.test.js
  test/unit/services/caseOrchestrationService.test.js
  test/unit/steps/petitionerProgressBar.test.js
Labels: ns:div-dn-pr-423

#434 DIV-5608: Updated Smart Survey URL
  app.js
  infrastructure/variables.tf
  steps/done/Done.content.json
  steps/done/Done.html
  steps/petition-progress-bar/PetitionProgressBar.content.json
Labels: ns:div-dn-pr-434

#424 DIV-5916 - Landing Page: Pet more information needed content correct
  common/content.json
Labels: ns:div-dn-pr-424

#438 Updated text around /session endpoint in ReadMe.md
  README.md
Labels: ns:div-dn-pr-438

#439 DIV-6031 - Update refusal and clarification document names
  config/default.yml
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  steps/done/Done.content.json
  steps/petition-progress-bar/PetitionProgressBar.content.json
  steps/petition-progress-bar/PetitionProgressBar.step.js
  test/unit/steps/done.test.js
  test/unit/steps/petitionerProgressBar.test.js
Labels: ns:div-dn-pr-439

#440 DIV-6030 Enable refusal feature
  charts/div-dn/values.preview.template.yaml
  config/default.yml
  infrastructure/variables.tf
Labels: ns:div-dn-pr-440
