Repository hmcts/div-decree-nisi-frontend, pull requests merged in 2019-06, with the labels that each got.

#354 DN shows resp solicitor representation
  steps/review-aos-response/ReviewAosResponse.content.json
  steps/review-aos-response/ReviewAosResponse.step.js
  steps/review-aos-response/templates/ReviewResponse.html
  steps/review-aos-response/templates/ViewResponse.html
  test/unit/steps/reviewAosResponse.test.js
Labels: ns:div-dn-pr-354

#356 DIV-3999: Consolidate naming of responses in health check
  middleware/healthcheck.js
Labels: ns:div-dn-pr-356

#355 add certificate of entitlement to file list
  config/default.yml
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  steps/petition-progress-bar/PetitionProgressBar.content.json
  test/unit/steps/petitionerProgressBar.test.js
Labels: ns:div-dn-pr-355

#351 DIV-4622 screen reader reads case reference ID as seperate characters
  package.json
  steps/done/Done.html
  test/unit/views/filters/a11y.test.js
  test/w3cjs/index.js
  views/filters/a11y.js
Labels: ns:div-dn-pr-351

#358 Awaiting pronouncement with hearing date
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  sonar-project.properties
  steps/petition-progress-bar/PetitionProgressBar.step.js
  steps/petition-progress-bar/petitionerStateTemplates.js
  steps/petition-progress-bar/sections/awaitingPronouncement/PetitionProgressBar.awaitingPronouncement.template.html
  steps/petition-progress-bar/sections/awaitingPronouncement/PetitionProgressBar.content.awaitingPronouncement.json
  test/unit/steps/petitionerProgressBar.test.js
Labels: ns:div-dn-pr-358

#352 Updated look and feel version to latest, progress bar accessibility
  package.json
  yarn.lock
Labels: ns:div-dn-pr-352

#363 DIV-3264: Update readme
  .gitignore
  LICENSE.md
  README.md
  docker-compose.yaml
Labels: ns:div-dn-pr-363

#362 DIV-4881 - Petitioner DN pronounced landing page, and download
  config/default.yml
  middleware/checkCaseState.js
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  mocks/steps/modify-session/ModifySession.step.js
  mocks/steps/modify-session/sections/caseState.html
  mocks/steps/modify-session/sections/respondent.html
  steps/petition-progress-bar/PetitionProgressBar.content.json
  steps/petition-progress-bar/PetitionProgressBar.step.js
  steps/petition-progress-bar/petitionerStateTemplates.js
  steps/petition-progress-bar/sections/decreeNisiGranted/PetitionProgressBar.content.decreeNisiGranted.json
  steps/petition-progress-bar/sections/decreeNisiGranted/PetitionProgressBar.decreeNisiGranted.template.html
  test/e2e/journeys/ccdStates/awaitingDecreeAbsolute.test.js
  test/unit/middleware/checkCheckState.test.js
  test/unit/steps/petitionerProgressBar.test.js
Labels: ns:div-dn-pr-362

#367 DIV-5153 - Bold text on DN & AOS confirmation page
  steps/petition-progress-bar/sections/awaitingPronouncement/PetitionProgressBar.awaitingPronouncement.template.html
  steps/petition-progress-bar/sections/awaitingPronouncement/PetitionProgressBar.content.awaitingPronouncement.json
  test/unit/steps/petitionerProgressBar.test.js
Labels: ns:div-dn-pr-367
