Repository hmcts/div-decree-nisi-frontend, pull requests merged in 2019-08, with the labels that each got.

#385 Fixed Unit test issues
  config/testing.json
  middleware/helmet.js
  mocks/services/fees-and-payments/version/1/enforcement-fee/GET.mock
  package.json
  test/functional/paths/intergration.js
  test/unit/middleware/helmet.test.js
  test/unit/mocha-init.js
  test/unit/mocha.opts
  test/unit/services/idam.test.js
  test/unit/views/filters/a11y.test.js
  test/unit/views/filters/date.test.js
  yarn.lock
Labels: ns:div-dn-pr-385

#387 DIV-4001 - Upgrade to the latest nodejs version
  .nvmrc
  Dockerfile
  Jenkinsfile_CNP
  package.json
  yarn.lock
Labels: ns:div-dn-pr-387

#386 Div 4677 table layout needed instead of dl layout
  package.json
  steps/check-your-answers/CheckYourAnswers.content.json
  steps/check-your-answers/CheckYourAnswers.html
  views/check-your-answers.njk
  yarn.lock
Labels: ns:div-dn-pr-386

#390 DIV-5634 - Update vault definitions for DN, RFE and PFE
  Jenkinsfile_CNP
Labels: ns:div-dn-pr-390

#389 Fix heading structure
  package.json
  steps/check-your-answers/CheckYourAnswers.html
  views/includes/sideMenu.html
  yarn.lock
Labels: ns:div-dn-pr-389

#392 Fix cross browser tests
  bin/run-crossbrowser-tests.sh
  config/custom-environment-variables.yml
  config/default.yml
  test/crossbrowser/supportedBrowsers.js
  test/functional/pages/applyForDecreeNisi.js
  test/functional/pages/behaviourContinuedSinceApplication.js
  test/functional/pages/checkYouAnswers.js
  test/functional/pages/claimCosts.js
  test/functional/pages/miniPetition.js
  test/functional/pages/petitionerProgressBar.js
  test/functional/pages/privacyPolicy.step.js
  test/functional/pages/shareCourtDocuments.js
  test/functional/paths/intergration.js
Labels: ns:div-dn-pr-392

#393 retry request to validate html
  test/w3cjs/index.js
Labels: ns:div-dn-pr-393

#395 Update vault definitions on nightly
  Jenkinsfile_nightly
Labels: ns:div-dn-pr-395

#396 Upgraded Helm chart requirements to use hmctspublic
  charts/div-dn/Chart.yaml
  charts/div-dn/requirements.yaml
  charts/div-dn/values.aat.template.yaml
  charts/div-dn/values.preview.template.yaml
Labels: ns:div-dn-pr-396

#398 suppress zap known issues
  zapKnownIssues.xml
Labels: ns:div-dn-pr-398

#401 DIV-5694 Fix IDAM chart tags syntax
  charts/div-dn/values.preview.template.yaml
Labels: ns:div-dn-pr-401

#402 Revert chart update
  charts/div-dn/values.preview.template.yaml
Labels: ns:div-dn-pr-402
