Repository hmcts/div-decree-nisi-frontend, pull requests merged in 2019-02, with the labels that each got.

#251 DIV-4038 - add missing req parameter to logger statements
  mocks/services/evidenceManagmentService.js
  services/caseOrchestrationService.js
  services/evidenceManagmentService.js
  services/fileManagement.js
  services/logger.js
  test/unit/services/evidenceManagmentService.test.js
  test/unit/services/fileManagement.test.js
  test/unit/services/logger.test.js
Labels: ns:div-dn-pr-251

#259 update error messages
  steps/lived-apart-since-separation/LivedApartSinceSeparation.content.json
Labels: ns:div-dn-pr-259

#261 DIV-4234 - date of last behaviour incident can be since date of marriage
  steps/behaviour-continued-since-application/BehaviourContinuedSinceApplication.content.json
  steps/behaviour-continued-since-application/BehaviourContinuedSinceApplication.step.js
  test/unit/steps/behaviourContinuedSinceApplication.test.js
Labels: ns:div-dn-pr-261

#225 DIV-3041: Petitioner status page when resp does not admit adultery
  README.md
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  mocks/steps/modify-session/sections/caseState.html
  steps/petition-progress-bar/PetitionProgressBar.step.js
  steps/petition-progress-bar/petitionerStateTemplates.js
  steps/petition-progress-bar/sections/aosCompleted/PetitionProgressBar.aosCompleted.template.html
  steps/petition-progress-bar/sections/aosCompleted/PetitionProgressBar.content.aosCompleted.json
  steps/petition-progress-bar/sections/undefended/PetitionProgressBar.undefended.template.html
  test/e2e/journeys/ccdStates/aosCompleted.js
  test/e2e/journeys/ccdStates/aosSubmittedAwaitingAnswer.js
  test/e2e/journeys/ccdStates/dnAwaitingDeemedService.js
  test/e2e/journeys/ccdStates/dnAwaitingDefendedWithoutAnswer.js
  test/e2e/journeys/ccdStates/dnAwaitingDispensedWithService.js
  test/e2e/journeys/ccdStates/dnAwaitingUndefended.js
  test/unit/services/googleAnalytics.test.js
  test/unit/steps/petitionerProgressBar.test.js
  test/unit/steps/reviewAosResponse.test.js
  yarn.lock
Labels: ns:div-dn-pr-225

#240 Amend petition 3312
  config/custom-environment-variables.yml
  config/default.yml
  helpers/redirectToFrontendHelper.js
  infrastructure/main.tf
  kubernetes/config.aat.yaml
  mocks/services/case-orchestration/amend-petition/__/PUT.mock
  services/caseOrchestrationService.js
  steps/amend-application/AmendApplication.content.json
  steps/amend-application/AmendApplication.html
  steps/amend-application/AmendApplication.step.js
  steps/resp-not-admit-adultery/RespNotAdmitAdultery.step.js
  steps/review-aos-response/ReviewAosResponse.step.js
  test/e2e/journeys/ccdStates/aosCompleted.js
  test/functional/pages/amendApplication.step.js
  test/functional/paths/pages.js
  test/unit/helpers/redirectToFrontendHelper.test.js
  test/unit/services/caseOrchestrationService.test.js
  test/unit/steps/amendApplication.test.js
  test/unit/steps/respNotAdmitAdultery.test.js
Labels: ns:div-dn-pr-240

#262 Add CoRespondent Name to Review-Aos-Response
  steps/review-aos-response/ReviewAosResponse.content.json
  steps/review-aos-response/templates/ReviewResponse.html
  steps/review-aos-response/templates/ViewResponse.html
Labels: ns:div-dn-pr-262

#267 Div 3350 progressbar 2yearsep
  steps/petition-progress-bar/sections/aosCompleted/PetitionProgressBar.aosCompleted.template.html
  steps/petition-progress-bar/sections/aosCompleted/PetitionProgressBar.content.aosCompleted.json
  test/unit/steps/petitionerProgressBar.test.js
Labels: ns:div-dn-pr-267

#268 DIV-4272 - fixed broken tests when feature 5.2.0 is enabled
  test/e2e/journeys/DivorceReasons/adultery.test.js
  test/e2e/journeys/ccdStates/aosCompleted.js
  test/e2e/journeys/ccdStates/awaitingClarification.test.js
  test/e2e/journeys/ccdStates/awaitingConsideration.test.js
  test/e2e/journeys/ccdStates/awaitingPronouncement.test.js
  test/unit/steps/miniPetition.test.js
  test/unit/steps/petitionerProgressBar.test.js
  test/unit/steps/respNotAdmitAdultery.test.js
  test/unit/steps/reviewAosResponse.test.js
  test/unit/steps/shareCourtDocuments.test.js
Labels: ns:div-dn-pr-268

#254 CNP-1131 Activate ACR image build
  .dockerignore
  .gitignore
  Dockerfile
  README.md
  acb.tpl.yaml
  kubernetes/deployment.template.yaml
Labels: docker-optimisation, ns:div-dn-pr-254

#272 Update content for 'lived apart since desertion' page
  steps/lived-apart-since-desertion/LivedApartSinceDesertion.content.json
  steps/lived-apart-since-desertion/LivedApartSinceDesertion.html
  test/unit/steps/livedApartSinceDesertion.test.js
Labels: ns:div-dn-pr-272

#231 use progress list from look-and-feel
  app.js
  assets/scss/main.scss
  package.json
  steps/done/Done.html
  steps/petition-progress-bar/sections/awaitingSubmittedDN/PetitionProgressBar.awaitingSubmittedDN.template.html
  steps/petition-progress-bar/sections/deemedService/PetitionProgressBar.deemedService.template.html
  steps/petition-progress-bar/sections/defendedAwaitingAnswer/PetitionProgressBar.defendedAwaitingAnswer.template.html
  steps/petition-progress-bar/sections/defendedWithAnswer/PetitionProgressBar.defendedWithAnswer.template.html
  steps/petition-progress-bar/sections/defendedWithoutAnswer/PetitionProgressBar.defendedWithoutAnswer.template.html
  steps/petition-progress-bar/sections/dispensedWithService/PetitionProgressBar.dispensedWithService.template.html
  steps/petition-progress-bar/sections/issued/PetitionProgressBar.issued.template.html
  steps/petition-progress-bar/sections/respondentNotReplied/PetitionProgressBar.respondentNotReplied.template.html
  steps/petition-progress-bar/sections/submitted/PetitionProgressBar.submitted.template.html
  steps/petition-progress-bar/sections/undefended/PetitionProgressBar.undefended.template.html
  yarn.lock
Labels: ns:div-dn-pr-231

#275 Add missing styles and correct template
  assets/scss/main.scss
  steps/petition-progress-bar/sections/aosCompleted/PetitionProgressBar.aosCompleted.template.html
Labels: ns:div-dn-pr-275

#271 Changed text to align with other apps
  steps/mini-petition/MiniPetition.content.json
  steps/mini-petition/MiniPetition.html
  test/unit/steps/miniPetition.test.js
Labels: ns:div-dn-pr-271

#270 fix flow for 2 year sep
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  steps/petition-progress-bar/PetitionProgressBar.step.js
  test/e2e/journeys/DivorceReasons/separation2Years.test.js
  test/unit/steps/petitionerProgressBar.test.js
Labels: ns:div-dn-pr-270

#243 Div 3917 Dynamic fee display
  config/custom-environment-variables.yml
  config/default.yml
  infrastructure/main.tf
  kubernetes/config.aat.yaml
  middleware/feesAndPaymentsMiddleware.js
  middleware/healthcheck.js
  mocks/index.js
  mocks/services/fees-and-payments/version/1/amend-fee/GET.mock
  mocks/services/fees-and-payments/version/1/application-financial-order-fee/GET.mock
  mocks/services/fees-and-payments/version/1/application-without-notice-fee/GET.mock
  mocks/services/fees-and-payments/version/1/defended-petition-fee/GET.mock
  mocks/services/fees-and-payments/version/1/general-application-fee/GET.mock
  mocks/services/fees-and-payments/version/1/petition-issue-fee/GET.mock
  services/feesAndPaymentsService.js
  steps/amend-application/AmendApplication.content.json
  steps/amend-application/AmendApplication.step.js
  steps/dn-no-response/DnNoResponse.content.json
  steps/dn-no-response/DnNoResponse.step.js
  steps/mini-petition/MiniPetition.content.json
  steps/mini-petition/MiniPetition.step.js
  steps/petition-progress-bar/PetitionProgressBar.step.js
  steps/petition-progress-bar/sections/aosCompleted/PetitionProgressBar.content.aosCompleted.json
  steps/resp-not-admit-adultery/RespNotAdmitAdultery.content.json
  steps/resp-not-admit-adultery/RespNotAdmitAdultery.step.js
  test/e2e/journeys/DivorceReasons/adultery.test.js
  test/e2e/journeys/DivorceReasons/desertion.test.js
  test/e2e/journeys/DivorceReasons/separation2Years.test.js
  test/e2e/journeys/DivorceReasons/separation5Years.test.js
  test/e2e/journeys/DivorceReasons/unreasonablebehaviour.test.js
  test/e2e/journeys/ccdStates/aosCompleted.js
  test/e2e/journeys/ccdStates/aosOverdue.js
  test/e2e/journeys/ccdStates/aosStarted.test.js
  test/e2e/journeys/ccdStates/aosSubmittedAwaitingAnswer.js
  test/e2e/journeys/ccdStates/awaitingClarification.test.js
  test/e2e/journeys/ccdStates/awaitingConsideration.test.js
  test/e2e/journeys/ccdStates/awaitingLegalAdvisorReferal.test.js
  test/e2e/journeys/ccdStates/awaitingPronouncement.test.js
  test/e2e/journeys/ccdStates/defendedDivorce.test.js
  test/e2e/journeys/ccdStates/dnAwaitingDeemedService.js
  test/e2e/journeys/ccdStates/dnAwaitingDefendedWithoutAnswer.js
  test/e2e/journeys/ccdStates/dnAwaitingDispensedWithService.js
  test/e2e/journeys/ccdStates/dnAwaitingUndefended.js
  test/e2e/journeys/ccdStates/dnNoResponse.test.js
  test/e2e/journeys/ccdStates/submitted.test.js
  test/unit/middleware/feesAndPaymentsMiddleware.test.js
  test/unit/middleware/healthcheck.test.js
  test/unit/services/feesAndPaymentsService.test.js
  test/unit/services/googleAnalytics.test.js
  test/unit/steps/amendApplication.test.js
  test/unit/steps/dnNoResponse.test.js
  test/unit/steps/miniPetition.test.js
  test/unit/steps/petitionerProgressBar.test.js
  test/unit/steps/respNotAdmitAdultery.test.js
  test/w3cjs/index.js
Labels: ns:div-dn-pr-243
