Repository hmcts/div-decree-nisi-frontend, pull requests merged in 2020-12, with the labels that each got.

#505 Added crossbrowser tests for all browsers
  Jenkinsfile_nightly
  config/custom-environment-variables.yml
  config/default.yml
  test/crossbrowser/supportedBrowsers.js
  test/functional/helpers/JSWait.js
  test/functional/helpers/SauceLabsBrowserHelper.js
  test/functional/helpers/elementExist.js
  test/functional/helpers/idamHelper.js
  test/functional/pages/applyForDecreeNisi.js
  test/functional/pages/behaviourContinuedSinceApplication.js
  test/functional/pages/claimCosts.js
  test/functional/pages/done.step.js
  test/functional/pages/exit.step.js
  test/functional/pages/exitIntolerable.step.js
  test/functional/pages/idam.step.js
  test/functional/pages/intolerable.js
  test/functional/pages/miniPetition.js
  test/functional/pages/petitionerProgressBar.js
  test/functional/pages/respNotAdmitAdutlery.js
  test/functional/pages/shareCourtDocuments.js
  test/functional/pages/upload.js
  test/functional/paths/pages.js
  test/functional/saucelabs.conf.js
Labels: ns:divorce, prd:div, rel:div-dn-pr-505

#504 Enabled full functional tests
  package.json
  test/functional/pages/livedApartSinceAdultery.js
Labels: ns:divorce, prd:div, rel:div-dn-pr-504

#506 DIV-6645: Add content for Served by alternative method
  helpers/petitionHelper.js
  mocks/steps/modify-session/ModifySession.content.json
  mocks/steps/modify-session/ModifySession.step.js
  mocks/steps/modify-session/sections/petitioner.html
  steps/petition-progress-bar/PetitionProgressBar.step.js
  steps/petition-progress-bar/petitionerStateTemplates.js
  steps/petition-progress-bar/sections/servedByAlternativeMethod/PetitionProgressBar.content.servedByAlternativeMethod.json
  steps/petition-progress-bar/sections/servedByAlternativeMethod/PetitionProgressBar.servedByAlternativeMethod.template.html
  steps/petition-progress-bar/sections/undefended/PetitionProgressBar.undefended.template.html
  test/unit/helpers/petitionHelper.test.js
  test/unit/steps/petitionerProgressBar.test.js
Labels: ns:divorce, prd:div, rel:div-dn-pr-506

#507 DIV-6646: Served by alternative method dn response page
  helpers/petitionHelper.js
  steps/apply-for-decree-nisi/ApplyForDecreeNisi.content.json
  steps/apply-for-decree-nisi/ApplyForDecreeNisi.html
  steps/apply-for-decree-nisi/ApplyForDecreeNisi.step.js
  test/unit/helpers/petitionHelper.test.js
  test/unit/steps/applyForDecreeNisi.test.js
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-dn-pr-507
