Repository hmcts/div-decree-nisi-frontend, pull requests merged in 2020-10, with the labels that each got.

#492 upgrade AzureRM
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:divorce, prd:div, rel:div-dn-pr-492

#491 RPET361: fix cve vulnerabilities
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-dn-pr-491

#494 Fixed Pa11y Reporting
  package.json
Labels: ns:divorce, prd:div, rel:div-dn-pr-494

#490 DIV-6516: Display general orders document
  config/default.yml
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  steps/done/Done.content.json
  steps/petition-progress-bar/PetitionProgressBar.content.json
  test/unit/steps/done.test.js
  test/unit/steps/petitionerProgressBar.test.js
Labels: ns:divorce, prd:div, rel:div-dn-pr-490
