Repository hmcts/div-decree-nisi-frontend, pull requests merged in 2020-11, with the labels that each got.

#493 RPET-368: update bailiff fee and landing page
  steps/dn-no-response/DnNoResponse.content.json
  steps/dn-no-response/DnNoResponse.html
  steps/dn-no-response/DnNoResponse.step.js
Labels: ns:divorce, prd:div, rel:div-dn-pr-493

#497 TA-106 - Add accessibility for welsh tests
  test/a11y/index.js
Labels: ns:divorce, prd:div, rel:div-dn-pr-497

#498 TA-154: Decree nisi e2e welsh tests
  assets/js/documentUpload.js
  package.json
  steps/lived-apart-since-adultery/LivedApartSinceAdultery.content.json
  steps/mini-petition/MiniPetition.content.json
  steps/upload/Upload.html
  test/functional/helpers/JSWait.js
  test/functional/pages/accessibilityStatement.step.js
  test/functional/pages/adulteryFirstFoundOut.js
  test/functional/pages/amendApplication.step.js
  test/functional/pages/applyForDecreeNisi.js
  test/functional/pages/behaviourContinuedSinceApplication.js
  test/functional/pages/checkYouAnswers.js
  test/functional/pages/claimCosts.js
  test/functional/pages/contactDivorceTeam.js
  test/functional/pages/contactDivorceTeamError.js
  test/functional/pages/cookie.step.js
  test/functional/pages/courtFeedback.js
  test/functional/pages/desertionAskedToResumeDN.js
  test/functional/pages/dnNoResponse.js
  test/functional/pages/done.step.js
  test/functional/pages/exit.step.js
  test/functional/pages/exitIntolerable.step.js
  test/functional/pages/intolerable.js
  test/functional/pages/livedApartSinceAdultery.js
  test/functional/pages/livedApartSinceDesertion.js
  test/functional/pages/livedApartSinceLastIncidentDate.js
  test/functional/pages/livedApartSinceSeparation.js
  test/functional/pages/miniPetition.js
  test/functional/pages/petitionerProgressBar.js
  test/functional/pages/privacyPolicy.step.js
  test/functional/pages/respNotAdmitAdutlery.js
  test/functional/pages/reviewAosResponse.js
  test/functional/pages/reviewAosResponseFromCoRespondent.js
  test/functional/pages/shareCourtDocuments.js
  test/functional/pages/termsAndCondiction.step.js
  test/functional/pages/upload.js
  test/functional/paths/intergration.js
  test/functional/paths/pages.js
Labels: ns:divorce, prd:div, rel:div-dn-pr-498

#488 Div 6231 Text to show when proceed because of deemed or dispensed approved
  steps/apply-for-decree-nisi/ApplyForDecreeNisi.content.json
  steps/apply-for-decree-nisi/ApplyForDecreeNisi.html
  steps/apply-for-decree-nisi/ApplyForDecreeNisi.step.js
  steps/petition-progress-bar/PetitionProgressBar.content.json
  steps/petition-progress-bar/PetitionProgressBar.step.js
  steps/petition-progress-bar/sections/deemedApproved/PetitionProgressBar.content.deemedApproved.json
  steps/petition-progress-bar/sections/dispensedApproved/PetitionProgressBar.content.dispensedApproved.json
  test/unit/steps/applyForDecreeNisi.test.js
Labels: ns:divorce, prd:div, rel:div-dn-pr-488

#500 DIV-6180-served-by-process-server-dn-your-husband-wife-response-page
  helpers/petitionHelper.js
  mocks/steps/modify-session/ModifySession.content.json
  mocks/steps/modify-session/ModifySession.step.js
  mocks/steps/modify-session/sections/petitioner.html
  mocks/steps/modify-session/sections/respondent.html
  steps/apply-for-decree-nisi/ApplyForDecreeNisi.content.json
  steps/apply-for-decree-nisi/ApplyForDecreeNisi.html
  steps/apply-for-decree-nisi/ApplyForDecreeNisi.step.js
  steps/petition-progress-bar/PetitionProgressBar.step.js
  steps/petition-progress-bar/petitionerStateTemplates.js
  steps/petition-progress-bar/sections/processServerService/PetitionProgressBar.content.processServerService.json
  steps/petition-progress-bar/sections/processServerService/PetitionProgressBar.processServerService.template.html
  test/unit/helpers/petitionHelper.test.js
  test/unit/steps/applyForDecreeNisi.test.js
  test/unit/steps/petitionerProgressBar.test.js
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-dn-pr-500

#502 DIV-6179: Served by process server - update DN landing page
  helpers/petitionHelper.js
  mocks/steps/modify-session/ModifySession.content.json
  mocks/steps/modify-session/ModifySession.step.js
  mocks/steps/modify-session/sections/respondent.html
  test/unit/helpers/petitionHelper.test.js
Labels: ns:divorce, prd:div, rel:div-dn-pr-502

#503 Feature/upgrade crossbrowser dependencies
  Jenkinsfile_nightly
  config/custom-environment-variables.yml
  config/default.yml
  package.json
  test/crossbrowser/supportedBrowsers.js
  test/functional/codecept.conf.js
  test/functional/codecept.overnight.conf.js
  test/functional/helpers/JSWait.js
  test/functional/helpers/SauceLabsReportingHelper.js
  test/functional/helpers/caseConfigHelper.js
  test/functional/helpers/elementExist.js
  test/functional/helpers/urlHelper.js
  test/functional/paths/intergration.js
  test/functional/paths/pages.js
  test/functional/saucelabs.conf.js
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-dn-pr-503
