Repository hmcts/div-decree-nisi-frontend, pull requests merged in 2020-01, with the labels that each got.

#445 Delete ASE
  Jenkinsfile_CNP
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:div-dn-pr-445

#446 Bump dependencies to remove high vulnerabilities
  package.json
  yarn.lock
Labels: ns:divorce, rel:div-dn-pr-446

#448 Bumped Node version to 12.14.1
  .nsprc
  .nvmrc
  Dockerfile
  LICENSE.md
  README.md
  infrastructure/variables.tf
  package.json
  yarn.lock
Labels: ns:divorce, rel:div-dn-pr-448

#449 Fixed typo in ReadMe command
  README.md
  package.json
Labels: ns:divorce, rel:div-dn-pr-449
