Repository hmcts/div-decree-nisi-frontend, pull requests merged in 2020-07, with the labels that each got.

#481 WLA-591: Welsh copy amends
  steps/mini-petition/MiniPetition.content.json
  steps/review-aos-response/ReviewAosResponse.content.json
Labels: ns:divorce, prd:div, rel:div-dn-pr-481

#482 Update Terraform provider
  infrastructure/main.tf
Labels: ns:divorce, prd:div, rel:div-dn-pr-482

#483 Remove yarn audit as its now run elsewhere
  Jenkinsfile_CNP
Labels: ns:divorce, prd:div, rel:div-dn-pr-483

#480 WLA-590: Enable Language Toggle on UI
  package.json
  views/includes/phase_banner.html
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-dn-pr-480

#484 add resolutions to package.json to fix CVE's
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-dn-pr-484

#486 change look-and-feel version
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-dn-pr-486

#485 Re-enable e2e
  package.json
  test/functional/codecept.conf.js
  test/functional/paths/pages.js
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-dn-pr-485
