Repository hmcts/div-decree-nisi-frontend, pull requests merged in 2021-12, with the labels that each got.

#571 DFR-690: Upgrade properties volume- REVERT
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-dn-pr-571

#572 DFR-690: Upgrade properties volume
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-dn-pr-572

#575 DFR-708: remove deprecated code dn
  .env
  .gitignore
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:divorce, prd:div, rel:div-dn-pr-575

#576 Update app.js
  app.js
Labels: ns:divorce, prd:div, rel:div-dn-pr-576

#577 DFR-701: Upgrade redis
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-dn-pr-577

#580 DFR-736: update fortify release id
  test/java/config/fortify-client.properties
Labels: ns:divorce, prd:div, rel:div-dn-pr-580
