Repository hmcts/div-decree-nisi-frontend, pull requests merged in 2021-03, with the labels that each got.

#522 DIV-5463: New page for served by bailiff unsuccessful
  mocks/steps/modify-session/ModifySession.content.json
  mocks/steps/modify-session/ModifySession.html
  mocks/steps/modify-session/ModifySession.step.js
  mocks/steps/modify-session/sections/serviceApplication.html
  steps/dn-no-response/DnNoResponse.html
  steps/petition-progress-bar/PetitionProgressBar.step.js
  steps/petition-progress-bar/petitionerStateTemplates.js
  steps/petition-progress-bar/sections/aosCompleted/PetitionProgressBar.aosCompleted.template.html
  steps/petition-progress-bar/sections/bailiffServiceNotSuccessful/PetitionProgressBar.bailiffServiceNotSuccessful.template.html
  steps/petition-progress-bar/sections/bailiffServiceNotSuccessful/PetitionProgressBar.content.bailiffServiceNotSuccessful.json
  test/unit/steps/petitionerProgressBar.test.js
  views/includes/aos_delivery_alternatives.html
Labels: ns:divorce, prd:div, rel:div-dn-pr-522

#523 DIV-5462: New landing page: Bailiff served successfully
  steps/petition-progress-bar/petitionerStateTemplates.js
  steps/petition-progress-bar/sections/bailiffServiceSuccessful/PetitionProgressBar.bailiffServiceSuccessful.template.html
  steps/petition-progress-bar/sections/bailiffServiceSuccessful/PetitionProgressBar.content.bailiffServiceSuccessful.json
  test/unit/steps/petitionerProgressBar.test.js
Labels: ns:divorce, prd:div, rel:div-dn-pr-523

#524 Div 5457 Alphabetise case state
  middleware/checkCaseState.js
Labels: ns:divorce, prd:div, rel:div-dn-pr-524

#527 DIV-5457: Redirect IssuedToBailiff and AwaitingBailiffService
  config/default.yml
Labels: ns:divorce, prd:div, rel:div-dn-pr-527

#526 DIV-6225: Add SuccessfulServedByBailiff AosOverdue Page
  helpers/petitionHelper.js
  steps/petition-progress-bar/PetitionProgressBar.step.js
  steps/petition-progress-bar/petitionerStateTemplates.js
  steps/petition-progress-bar/sections/bailiffServiceSuccessfulContinue/PetitionProgressBar.bailiffServiceSuccessfulContinue.template.html
  steps/petition-progress-bar/sections/bailiffServiceSuccessfulContinue/PetitionProgressBar.content.bailiffServiceSuccessfulContinue.json
  test/unit/helpers/petitionHelper.test.js
  test/unit/steps/petitionerProgressBar.test.js
Labels: ns:divorce, prd:div, rel:div-dn-pr-526

#529 Resolve y18n dependency
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-dn-pr-529

#519 RPET-664: Brexit changes
  steps/mini-petition/MiniPetition.content.json
  steps/mini-petition/MiniPetition.html
  test/unit/steps/miniPetition.test.js
Labels: ns:divorce, prd:div, rel:div-dn-pr-519
