Repository hmcts/div-decree-nisi-frontend, pull requests merged in 2021-01, with the labels that each got.

#509 DIV-6654: Map general referral states on Petitioner and Respondent apps
  mocks/steps/modify-session/ModifySession.step.js
  mocks/steps/modify-session/sections/caseState.html
  package.json
  test/unit/middleware/checkCheckState.test.js
Labels: ns:divorce, prd:div, rel:div-dn-pr-509

#511 Update axios and node-notifier
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-dn-pr-511

#512 RPET-660: nightly build new approach
  Jenkinsfile_nightly
  security.sh
Labels: ns:divorce, prd:div, rel:div-dn-pr-512
