Repository hmcts/div-decree-nisi-frontend, pull requests merged in 2021-05, with the labels that each got.

#536 RPET-981: Fix dependency checks
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-dn-pr-536

#537 fix CVE's
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-dn-pr-537

#539 postcss ^8.2.10
  audit.json
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-dn-pr-539

#541 Added safari to xb tests
  bin/run-crossbrowser-tests.sh
  test/crossbrowser/supportedBrowsers.js
Labels: ns:divorce, prd:div, rel:div-dn-pr-541

#542 RPET-1014: Downgrading redis
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-dn-pr-542
