Repository hmcts/div-decree-nisi-frontend, pull requests merged in 2022-05, with the labels that each got.

#622 DFR 979 Fix missing webchat title
  steps/avaya-webchat/AvayaWebchat.html
  views/includes/problem_with_this_page.html
Labels: bug, ns:divorce, prd:div, rel:div-dn-pr-622

#623 DFR-1045 Update contactCenterClosed text
  assets/locale/locale_en-GB.json
Labels: ns:divorce, prd:div, rel:div-dn-pr-623

#624 DFR-1044: Hide respondent address if confidential from the petitioner
  steps/petition-progress-bar/sections/respondentNotReplied/PetitionProgressBar.respondentNotReplied.template.html
Labels: ns:divorce, prd:div, rel:div-dn-pr-624

#628 Autoscaling
  charts/div-dn/Chart.yaml
  charts/div-dn/values.yaml
Labels: ns:divorce, prd:div, rel:div-dn-pr-628

#630 DFR-1086 Configure Pipelines for Additional Tests
  Jenkinsfile_CNP
  README.md
Labels: ns:divorce, prd:div, rel:div-dn-pr-630

#625 Dfr 612 remove feature toggles
  app.js
  charts/div-dn/Chart.yaml
  charts/div-dn/values.yaml
  config/custom-environment-variables.yml
  config/default.yml
  infrastructure/prod.tfvars
  infrastructure/variables.tf
  middleware/helmet.js
  package.json
  test/unit/middleware/helmet.test.js
  test/unit/views/contactus.test.js
  views/includes/problem_with_this_page.html
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-dn-pr-625, enable_all_tests_and_scans
