Repository hmcts/div-decree-nisi-frontend, pull requests merged in 2022-01, with the labels that each got.

#582 DFR-701: Upgrade One Per Page lib
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-dn-pr-582

#583 Dfr 701 redis ping
  charts/div-dn/Chart.yaml
  charts/div-dn/values.aat.template.yaml
  charts/div-dn/values.preview.template.yaml
  config/custom-environment-variables.yml
  config/default.yml
  services/redis.js
  sonar-project.properties
Labels: ns:divorce, prd:div, rel:div-dn-pr-583

#544 DFR-37 Deploy Cookie Banner for Dynatrace
  .eslintignore
  README.md
  app.js
  assets/js/cookiesManager.js
  assets/js/main.js
  assets/scss/_cookies.scss
  charts/div-dn/Chart.yaml
  charts/div-dn/values.preview.template.yaml
  charts/div-dn/values.yaml
  config/custom-environment-variables.yml
  config/default.yml
  package.json
  steps/cookies-policy/CookiesPolicy.content.json
  steps/cookies-policy/CookiesPolicy.html
  test/functional/pages/upload.js
  views/check-your-answers.njk
  views/errors/not-found-error.html
  views/errors/server-error.html
  views/includes/cookies/button/macro.njk
  views/includes/cookies/button/template.njk
  views/includes/cookies/cookie-banner/cookie.njk
  views/includes/cookies/cookie-banner/macro.njk
  views/includes/cookies/cookie-banner/template.njk
  views/includes/cookies/cookie-manager/cookie-banner.njk
  views/includes/cookies/cookie-manager/cookie-reject-all-banner.njk
  views/includes/cookies/cookie-manager/cookie-success-all-banner.njk
  views/includes/cookies/cookie-manager/cookie-success-banner.njk
  views/includes/head.html
  views/page.njk
  views/question.njk
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-dn-pr-544

#589 DFR-562: Add User Attribute
  steps/avaya-webchat/AvayaWebchat.html
Labels: ns:divorce, prd:div, rel:div-dn-pr-589

#590 DFR-37-Webchat-Fix
  assets/js/cookiesManager.js
Labels: ns:divorce, prd:div, rel:div-dn-pr-590

#592 Resolved header manipulation fortify errors
  assets/js/cookiesManager.js
  yarn-audit-known-issues
Labels: ns:divorce, prd:div, rel:div-dn-pr-592

#593 Adjust TLS method to TLS v1.2 method
  server.js
Labels: ns:divorce, prd:div, rel:div-dn-pr-593
