Repository hmcts/div-decree-nisi-frontend, pull requests merged in 2022-02, with the labels that each got.

#594 Update cookiesManager.js
  assets/js/cookiesManager.js
Labels: ns:divorce, prd:div, rel:div-dn-pr-594

#597 dependency fixes
  charts/div-dn/Chart.yaml
  yarn-audit-known-issues
Labels: ns:divorce, prd:div, rel:div-dn-pr-597

#599 dependency fixes
  yarn-audit-known-issues
Labels: ns:divorce, prd:div, rel:div-dn-pr-599
